name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.0
  http: ^1.1.0
  universal_html: ^2.0.8
  flutter_speed_dial: ^7.0.0
  vector_math: ^2.1.4
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.2
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
    
  assets:
    - assets/images/

  fonts:
    - family: Playball
      fonts:
        - asset: assets/fonts/Playball-Regular.ttf
  

