name: ties_of_love_backend
description: Backend for Ties of Love app
environment:
  sdk: '^3.7.0'

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  postgres: ^2.6.4

dev_dependencies:
  lints: ^2.1.1